services:
  habitsync_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: habit-sync
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  habitsync_app:
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - habitsync_database

volumes:
  pgdata:
